// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebLibrary.Model
{
    [Table("Livro_Cliente_Emprestimo")]
    public partial class LivroClienteEmprestimo
    {
        [Key]
        [Display(Name = "Código")]
        [Column("id")]
        public int Id { get; set; }

        [Display(Name = "Código do livro")]
        [Column("idLivro")]
        public int IdLivro { get; set; }

        [Display(Name = "Código do cliente")]
        [Column("idCliente")]
        public int IdCliente { get; set; }

        [Display(Name = "Data de empréstimo")]
        [Column("dataEmprestimo", TypeName = "datetime")]
        public DateTime DataEmprestimo { get; set; }

        [Display(Name = "Data de devolução")]
        [Column("dataDevolucao", TypeName = "datetime")]
        public DateTime DataDevolucao { get; set; }

        [ForeignKey(nameof(IdCliente))]
        [Display(Name = "Código do cliente")] // Data Annotations
        [InverseProperty(nameof(Cliente.LivroClienteEmprestimo))]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey(nameof(IdLivro))]
        [Display(Name = "Código do livro")] // Data Annotations
        [InverseProperty(nameof(Livro.LivroClienteEmprestimo))]
        public virtual Livro IdLivroNavigation { get; set; }
    }
}